### PR TITLE
Update download link to point to 4am build

### PR DESCRIPTION
**Pull request by zellyn**

### CODE REVIEW

**Comment by zellyn** [comment]
@tobier hey would you mind merging this, or giving me merge access? Thanks!

**Comment by zellyn** [comment]
ping

**Comment by tobier** [comment]
@zellyn Sorry for the very, _very_ slow merge. I have added the team to have write permissions to this repository.

**Comment by zellyn** [comment]
No problem!  This is a hobby project, and we all get busy :-)

**Comment by zellyn** [comment]
btw, since I don't see you on there, the Apple2Infinitum Slack has turned into a really vital and active community… http://apple2.gs:3000/

**Comment by tobier** [comment]
@zellyn i will check it out!

**Pull request merged**
